const imageUrls = [
    'assets/Adventureland_3D.jpg',
    'assets/Cover 2D.jpg',
    'assets/The Gorilla Shake.jpg',
    'assets/Snack Sparrow.jpg',
    'assets/Trucks Playing Tricks.jpg',
    'assets/Toilet Ladies.jpg',
    'assets/Tronville.jpg',
    'assets/Rock & Roll Ride.jpg',
    'assets/Perfect waves.jpg',
    'assets/Miami Vibes.jpg',
    'assets/Daddy Love.jpg',
    'assets/Award card.jpg',

];

const reviews = [
    {
        name: "markmasters",
        rating: 9,
        comment: "Played at Spiel. Fun game with a nice mechanic that allows either to pick first or grants money.",
        link: "https://boardgamegeek.com/boardgame/356630/adventure-land/ratings#:~:text=9-,markmasters,-Oct%202023",
    },
    {
        name: "oldmartijntje",
        rating: 10,
        comment: "Awesome game, fun for all ages. The art is on point, with a lot of fun jokes. The production quality is good. The gameplay mechanics are very fun. Everyone I talk to about this game likes it. Even if you think you are losing mid game, you can still win in the end. I would recommend this to pretty much every type of player. Because you can play it casually or very strategic, and both types of players can win.",
        link: "https://boardgamegeek.com/boardgame/356630/adventure-land/ratings#:~:text=10-,oldmartijntje,-Oct%202023",
    },
    {
        name: "hollandiase",
        comment: "Wat een leuk spel is dit! Bieden, bluffen, betalen,sparen,setcollection.. er zit van alles in. En daarnaast ook nog eens spannend!",
        link: "https://www.instagram.com/p/CyBzqv1Lm8m/?igshid=MzRlODBiNWFlZA==",
    },
    {
        name: "Brainmaster",
        rating: 9,
        comment: "",
        link: "https://boardgamegeek.com/boardgame/356630/adventure-land/ratings#:~:text=9-,Brainmaster,-Sep%202023",
    },
    {
        name: "Mielesgames",
        rating: 10,
        comment: "It's an awesome game, 10/10 it's perfect!",
        link: "https://boardgamegeek.com/boardgame/356630/adventure-land/ratings#:~:text=10-,Mielesgames,-Oct%202023",
    },
    {
        name: "de Beek",
        rating: 8,
        comment: "",
        link: "https://boardgamegeek.com/boardgame/356630/adventure-land/ratings#:~:text=8-,de%20Beek,-Oct%202023",
    },
    {
        name: "bridgetvh",
        rating: 8,
        comment: "",
        link: "https://boardgamegeek.com/thread/3159354/review-bordspelwereldnl-dutch",
    },
];

const translations = {
    "EN": {
        "T.title": "Adventure Land Board Game",
        "T.headerTitle": "Adventure Land - Build Your Dream Park",
        "prevButton": "Previous",
        "nextButton": "Next",
        "T.infoTitle1": "Build Your Dream Park!",
        "T.infoText1": "In Adventure Land, start your journey to create the most exciting theme park. Build thrilling attractions, hire the best staff, and invest your money wisely. Complete secret missions to boost the popularity of your park. The ultimate goal is to win the prestigious Award!",
        "T.infoTitle2": "One Grand Adventure",
        "T.infoText2": "Adventure Land feels like a huge roller coaster ride. In just one hour, so much happens that you'll need a moment to catch your breath. It all starts with the auction of the parks. Each park looks completely different in every game. Which one will you choose? This jumpstart gives you certain opportunities and possible strategies right from the start. Will you specialize in a particular theme? Or will you hire valuable staff? Will you decide to hire janitors and cash in on every restroom built, or will you play it safe and hire a gardener for a stable income stream? The choice is yours!",
        "T.reviewsTitle": "Reviews",
        "prevReviewButton": "Previous Review",
        "nextReviewButton": "Next Review",
        "T.linksTitle": "Links:",
        "T.instagram": "Instagram",
        "T.theGameMaster": "TheGameMaster",
        "T.boardGameGeek": "BoardGameGeek",
        "download-link": "Download Rules PDF",
        "T.reviewLink": "Original Post",
        "T.reviewRating": "Rating"
    },
    "NL": {
        "T.title": "Adventure Land Bordspel",
        "T.headerTitle": "Adventure Land - Bouw Jouw Droompark",
        "prevButton": "Vorige",
        "nextButton": "Volgende",
        "T.infoTitle1": "Bouw Jouw Droompark!",
        "T.infoText1": "In Adventure Land begint je reis om het meest opwindende themapark te creëren. Bouw spannende attracties, huur het beste personeel in en investeer je geld wijselijk. Voltooi geheime missies om de populariteit van je park te vergroten. Het ultieme doel is om de prestigieuze Award te winnen!",
        "T.infoTitle2": "Een Groots Avontuur",
        "T.infoText2": "Adventure Land voelt als een enorme achtbaanrit. In slechts één uur gebeurt er zo veel dat je even moet bijkomen. Het begint allemaal met de veiling van de parken. Elk park ziet er in elk spel volledig anders uit. Welke kies je? Deze kickstart biedt je bepaalde kansen en mogelijke strategieën vanaf het begin. Zal je je specialiseren in een bepaald thema? Of zal je waardevol personeel aannemen? Besluit je om schoonmakers in dienst te nemen en geld te verdienen met elke gebouwde wc, of speel je het veilig en neem je een tuinman voor een stabiele inkomstenstroom? De keuze is aan jou!",
        "T.reviewsTitle": "Recensies",
        "prevReviewButton": "Vorige Recensie",
        "nextReviewButton": "Volgende Recensie",
        "T.linksTitle": "Links:",
        "T.instagram": "Instagram",
        "T.theGameMaster": "TheGameMaster",
        "T.boardGameGeek": "BoardGameGeek",
        "download-link": "Download Spelregels PDF",
        "T.reviewLink": "Origineel Bericht",
        "T.reviewRating": "Beoordeling"
    },
    "FR": {
        "T.title": "Jeu de Société Aventure Land",
        "T.headerTitle": "Aventure Land - Construisez Votre Parc de Rêve",
        "prevButton": "Précédent",
        "nextButton": "Suivant",
        "T.infoTitle1": "Construisez Votre Parc de Rêve !",
        "T.infoText1": "Dans Aventure Land, lancez votre voyage pour créer le parc à thème le plus excitant. Construisez des attractions palpitantes, engagez le meilleur personnel et investissez votre argent judicieusement. Accomplissez des missions secrètes pour augmenter la popularité de votre parc. L'objectif ultime est de remporter le prestigieux Prix !",
        "T.infoTitle2": "Une Aventure Grandiose",
        "T.infoText2": "Aventure Land donne l'impression d'un grand manège de montagnes russes. En seulement une heure, tant de choses se passent que vous aurez besoin d'un moment pour reprendre votre souffle. Tout commence par la vente aux enchères des parcs. Chaque parc est complètement différent à chaque partie. Lequel choisirez-vous ? Ce coup d'envoi vous offre certaines opportunités et des stratégies possibles dès le départ. Vous spécialiserez-vous dans un thème particulier ? Ou embaucherez-vous du personnel précieux ? Déciderez-vous d'embaucher des agents d'entretien et d'encaisser chaque toilette construite, ou jouerez-vous la sécurité en embauchant un jardinier pour un revenu stable ? Le choix vous appartient !",
        "T.reviewsTitle": "Avis",
        "prevReviewButton": "Avis Précédent",
        "nextReviewButton": "Avis Suivant",
        "T.linksTitle": "Liens :",
        "T.instagram": "Instagram",
        "T.theGameMaster": "TheGameMaster",
        "T.boardGameGeek": "BoardGameGeek",
        "download-link": "Télécharger les Règles en PDF",
        "T.reviewLink": "Publication Originale",
        "T.reviewRating": "Évaluation"
    },
    "DE": {
        "T.title": "Adventure Land Brettspiel",
        "T.headerTitle": "Adventure Land - Baue deinen Traumpark",
        "prevButton": "Vorherige",
        "nextButton": "Nächste",
        "T.infoTitle1": "Baue deinen Traumpark!",
        "T.infoText1": "In Adventure Land beginnt deine Reise, um den aufregendsten Themenpark zu erschaffen. Baue aufregende Attraktionen, stelle das beste Personal ein und investiere dein Geld klug. Erfülle geheime Missionen, um die Beliebtheit deines Parks zu steigern. Das ultimative Ziel ist, die angesehene Auszeichnung zu gewinnen!",
        "T.infoTitle2": "Ein Großes Abenteuer",
        "T.infoText2": "Adventure Land fühlt sich an wie eine riesige Achterbahnfahrt. In nur einer Stunde passiert so viel, dass du einen Moment brauchst, um Luft zu holen. Alles beginnt mit der Versteigerung der Parks. Jeder Park sieht in jedem Spiel völlig anders aus. Welchen wählst du? Dieser Kickstart bietet dir von Anfang an bestimmte Möglichkeiten und mögliche Strategien. Wirst du dich auf ein bestimmtes Thema spezialisieren? Oder wirst du wertvolles Personal einstellen? Wirst du dich entscheiden, Reinigungskräfte einzustellen und mit jeder gebauten Toilette Geld zu verdienen, oder wirst du es sicher spielen und einen Gärtner für ein stabiles Einkommen einstellen? Die Wahl liegt bei dir!",
        "T.reviewsTitle": "Bewertungen",
        "prevReviewButton": "Vorherige Bewertung",
        "nextReviewButton": "Nächste Bewertung",
        "T.linksTitle": "Links:",
        "T.instagram": "Instagram",
        "T.theGameMaster": "TheGameMaster",
        "T.boardGameGeek": "BoardGameGeek",
        "download-link": "Spielregeln als PDF herunterladen",
        "T.reviewLink": "Ursprünglicher Beitrag",
        "T.reviewRating": "Bewertung"
    }
};
